### ISSUE TITLE
How to get the HTML profile report?

### ISSUE THREAD

**Issue by the-james-burton** [zolyfarkas/spf4j#19]
Hi, your docs talk about a HTML report for he profiling, but I am unable to get it created. When I try to run it it does not have the -f option in the usage output...

```
Error: "-f" is not a valid option
Usage:
 -df VAL   : dump folder (default: /tmp)
 -di N     : the stack dump to file interval in milliseconds (default: 3600000)
 -dp VAL   : dump file prefix (default: 7850@x220t)
 -main VAL : the main class name
 -si N     : the stack sampling interval in milliseconds (default: 100)
 -ss       : start the stack sampling thread. (can also be done manually via
             jmx) (default: false)
```

Without the -f option it works fine and I can load the output into the spf4j-ui. I am using v8.3.5. My command line is

```
-df /tmp -f /tmp/spf4j.profile.html -dp spf4j -ss -si 10  -main performance.Main
```
Thanks,
James

**Comment by zolyfarkas** [comment]
Hi, the HTML report was decommissioned a while ago, will have to update the documentation.

The current usage is:

Usage:
 -df VAL   : dump folder (default: current folder)
 -di N     : the stack dump to file interval in milliseconds (default: 3600000)
 -dp VAL   : dump file prefix (default: ManagementFactory.getRuntimeMXBean().getName())
 -main VAL : the main class name
 -si N     : the stack sampling interval in milliseconds (default: 100)
 -ss       : start the stack sampling. (can also be done manually via
             jmx) (default: false)

profiling data will be saved into ssdump files. that can be opened with the spf4j ui: http://search.maven.org/remotecontent?filepath=org/spf4j/spf4j-ui/8.3.5/spf4j-ui-8.3.5-uber.jar 

The UI allows for better visualization and more importantly filtering..

let me know if you have any questions.

**Comment by zolyfarkas** [comment]
Updated documentation.

**Comment by the-james-burton** [comment]
Ok thanks for letting me know.
