### ISSUE TITLE
What is the correct property for config?

### ISSUE THREAD

**Issue by the-james-burton** [zolyfarkas/spf4j#20]
Your docs say to use `perf.ms.config` as a JVM arg to specify the output directory. I noticed this wasn't working, so I looked through the code and I found that it might be `spf4j.perf.ms.config`. When I used this instead, it worked as expected.

Am I doing it wrong or do your docs simply need updating?

**Comment by zolyfarkas** [comment]
You are correct, the doc is out of date, will correct it.

**Comment by zolyfarkas** [comment]
Doc updated

**Comment by the-james-burton** [comment]
Ok, thanks for the clarification.
