### ISSUE TITLE
If txt output file does not exist, it should create it

### ISSUE THREAD

**Issue by the-james-burton** [zolyfarkas/spf4j#21]
If I send the txt output to a file that does not exist, I get this error...
```
java.nio.file.NoSuchFileException: /tmp/spf4j.metrics.tsdb.txt
```
Of course, all I need to do is touch the file before performance metrics start gathering and it works as expected...
```
com.google.common.io.Files.touch(new File("/tmp/spf4j.metrics.tsdb.txt"));
```
It does create the binary output file if it does not exist To be consistent, perhaps spf4j should also create the txt output file itself? I'm happy to raise a PR if you agree.

**Comment by zolyfarkas** [comment]
comited a fix, will be resolved in the next release.

thanks!

**Comment by the-james-burton** [comment]
That's great, thanks!
