### ISSUE TITLE
Dual license?

### ISSUE THREAD

**Issue by jtnelson** [zolyfarkas/spf4j#22]
Library looks very interesting and I'd like to use it in some of my open source projects but LGPL is incompatible with the Apache License 2.0. Would it be possible to dual license this library as MIT or Apache in addition to the current LGPL license?

**Comment by zolyfarkas** [comment]
I am no license expert but in my opinion LGPL is compatible with apache.
However since this does not seem to be the overwhelming consensus I am OK licensing it with APACHE License as well.

**Comment by jtnelson** [comment]
Great! Should I submit a PR updating the license to indicate the duality?

**Comment by zolyfarkas** [comment]
No need, I will push the change shortly.

thank you

—Z

**Comment by zolyfarkas** [comment]
8.3.6 is out with updated licensing.
