### ISSUE TITLE
org.spf4j.stackmonitor.Sampler.dumpToFile(String) appends colon to filename which is not valid in Windows

### ISSUE THREAD

**Issue by jonathan-m-foley** [zolyfarkas/spf4j#28]
Awesome library! Minor issue I ran into with the org.spf4j.stackmonitor.Sampler - the generated filename w/ timestamp contains colon characters, which are not valid in Windows filenames.
[Around line 262](https://github.com/zolyfarkas/spf4j/blob/master/spf4j-core/src/main/java/org/spf4j/stackmonitor/Sampler.java#L262)
```
/**
   * Dumps the sampled stacks to file. the collected samples are reset
   *
   * @param id - id will be added to file name returns the name of the file.
   * @return - the file name where the data was persisted or null if there was no data to persist.
   * @throws IOException - io issues while persisting data.
   */
  @JmxExport(value = "dumpToSpecificFile", description = "save stack samples to file")
  @Nullable
  @SuppressFBWarnings("PATH_TRAVERSAL_IN") // not possible the provided ID is validated for path separators.
  public synchronized File dumpToFile(
          @JmxExport(value = "fileID", description = "the ID that will be part of the file name")
          @Nullable final String id) throws IOException {
    String fileName = filePrefix + CharSequences.validatedFileName(((id == null) ? "" : '_' + id) + '_'
            + DateTimeFormats.TS_FORMAT.format(Timing.getCurrentTiming().fromNanoTimeToInstant(lastDumpTimeNanos))
            + '_' + DateTimeFormats.TS_FORMAT.format(Instant.now()));
    File file = new File(dumpFolder, fileName);
    return dumpToFile(file);
  }
```

**Comment by zolyfarkas** [comment]
Thanks, pushed a fix to latest DEV build (8.5.6-SNAPSHOT) which should be in maven central to try out.

let me know if this works or not.

—Z

**Comment by jonathan-m-foley** [comment]
Great, I saw your fix on master.  I appreciate the quick response, that looks like it will work. I'm not seeing the [snapshot on maven-central](https://search.maven.org/search?q=g:org.spf4j%20AND%20a:spf4j-core%20AND%20v:8.5.6-SNAPSHOT) however.  I can try building it locally and verifying the fix tomorrow.

**Comment by jonathan-m-foley** [comment]
Tried it out and can confirm that this was fixed in https://github.com/zolyfarkas/spf4j/releases/tag/spf4j-8.5.6, thanks!
