### ISSUE TITLE
There is way to Suppress error about not expected error in log? 

### ISSUE THREAD

**Issue by mikolajmitura** [zolyfarkas/spf4j#37]
I meant this one: 
'Most test should not log errors, if a error scenario is validated, please assert this behavior using TestLoggers.expect'
Exists some globally configuration for that?

**Comment by zolyfarkas** [comment]
yes, there is.

there is a system property you can set, here is how to set with surefire:

```
  <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <systemProperties>
            <spf4j.testLog.expectingErrorsIn>org.aspectj.weaver.bcel.BcelWorld,... add other loggers where unit tests should not fail ...</spf4j.testLog.expectingErrorsIn>
....
```

will update the documentation.

**Comment by mikolajmitura** [comment]
I have configuration like this:  

        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <classpathDependencyExcludes>
                        <classpathDependencyExcludes>org.slf4j:slf4j-simple</classpathDependencyExcludes>
                    </classpathDependencyExcludes>
                    <systemProperties>
                        <spf4j.testLog.expectingErrorsIn>full.path.to.MyClass</spf4j.testLog.expectingErrorsIn> 
                    </systemProperties>
                    <properties>
                        <property>
                            <name>listener</name>
                            <value>org.spf4j.test.log.junit4.Spf4jTestLogRunListener</value> 
                        </property>
                    </properties>
                </configuration>
            </plugin>
        </plugins>

But still I got "Most test should not log errors, if a error scenario is validated, please assert this behavior using TestLoggers.expect, received:"

I understand that spf4j.testLog.expectingErrorsIn should have logger name, package, or full name of class which contains logger.

**Comment by zolyfarkas** [comment]
8.6.14 requires full logger name. (the string param of LoggerFactory.getLogger)
I have added a test and everything seems to work as expected.

In 8.6.15-SNAPSHOT I have added support for package (or category) names as well. It is in maven central, so  if you are using package names give it a try.

**Comment by mikolajmitura** [comment]
I tested in 8.6.16, and is working fine, Intellij  cannot resolve listeners, but in maven process is working correctly.

**Comment by zolyfarkas** [comment]
@mikolajmitura there is a issue opened with Intelij  to address this:
https://youtrack.jetbrains.com/issue/IDEA-190385

Netbeans does a good jobs at this.
