### ISSUE TITLE
mvn deploy phase + nexus reposity failure

### ISSUE THREAD

**Issue by mpataki** [zolyfarkas/spf4j#44]
The existence of the `maven-avro-schema-plugin` plugin in a project breaks the `mvn deploy` phase if you're deploying to a nexus repository.

Here's an example error message:
```
[INFO] --- maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) @ avro-schemas ---
[INFO] Using alternate deployment repository nexus-snapshot::default::https://nexus.company.com/repository/maven-snapshots
Uploading to : https://nexus.company.com/repository/maven-snapshots/com/company/avro-schemas/20-04-12_20-35_d7d3aa1/avro-schemas-20-04-12_20-35_d7d3aa1.jar
Uploading to : https://nexus.company.com/repository/maven-snapshots/com/company/avro-schemas/20-04-12_20-35_d7d3aa1/avro-schemas-20-04-12_20-35_d7d3aa1.pom
Uploading to : https://nexus.company.com/repository/maven-snapshots/com/company/avro-schemas/20-04-12_20-35_d7d3aa1/avro-schemas-20-04-12_20-35_d7d3aa1-avsc.jar
Uploading to : https://nexus.company.com/repository/maven-snapshots/com/company/avro-schemas/20-04-12_20-35_d7d3aa1/avro-schemas-20-04-12_20-35_d7d3aa1-avroSources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.721 s
[INFO] Finished at: 2020-04-12T19:25:29-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) on project avro-schemas: ArtifactDeployerException: Failed to deploy artifacts: Could not transfer artifact com.company:avro-schemas:jar:20-04-12_20-35_d7d3aa1 from/to nexus-snapshot::default (https://nexus.company.com/repository/maven-snapshots): Unauthorized (401) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Don't let the `401 Unauthorized` error code mislead you. Nexus tends to through this error for a number of reasons that have nothing to do with credentials. I can confirm that the credentials I'm using work via deploying other projects with them. 

Further, if I package my avro application, then comment out the `maven-avro-schema-plugin` plugin, and attempt to deploy my jar, it works just fine. Leaving it present causes the above error.

With the plugin in play, the deploy phase attempts to upload two additional jar, ending with `-avroSources.jar` and `-avsc.jar`, to my nexus repository. I suspect these are violating some naming rule, or similar constraint, but I've unfortunately not been able to track down the exact source of the violation from nexus just yet. If I do, I'll report back.

At least for my use case, I don't believe these additional jars are necessary. If nothing else, it would be helpful if there were some mechanism provided which would let me turn off this behaviour as I really just need this plugin for it's `avro-compile` goal. Of course, if the jars were to upload without issue to nexus then I'd have no problem letting the plugin do this, alternatively. 

Thanks in advance.

**Comment by zolyfarkas** [comment]
I am using thte plugin to deploy to Nexus, artifactory and bintray without issues, so this might be some issue related with your particular instance. (see example deployed to nexus: https://search.maven.org/artifact/org.spf4j.avro/core-schema/1.0.0/jar)

can you run maven with the -X option to get full debug info and hopefully more insight into what the issue might be?

In case your instance does not accept these 2 artifacts, they are not actually necessary.

the avsc artifact is there to  facilitate publishing your schemas to maven and use maven as a schema repository. 

will add some flags to allow you to disable them.

**Comment by zolyfarkas** [comment]
Added:
<packageAvsc>true|false</packageAvsc>
<packageAvscSources>true|false</packageAvscSources>
in 8.8.2-SNAPSHOT

I hope they help.

**Comment by mpataki** [comment]
Thanks, it's interesting to know that you also use nexus and don't see the same issues that I do. I'm going to keep digging into this.

I'm using this snapshot version now and it does in fact prevent the additional jars from being packaged. Unfortunately, I am still seeing the same error, surprisingly. My diagnosis must not be correct. As I said, I'll keep digging in and I'll report back sometimes soon. It's helpful, at this point, that I can rule out the jars via this change -- so thanks for that.

**Comment by zolyfarkas** [comment]
@mpataki take a look at: https://blog.sonatype.com/2010/11/what-to-do-when-nexus-returns-401/

**Comment by mpataki** [comment]
My apologies for letting this issue hang! I'll close it after this comment.

Having hit a wall, I walked away from the problem. Returning to it tonight, I spend no more than 10 minutes before seeing the issue :roll_eyes: 

We've been using the same deploy pipeline for quite some time, and it seems made use of a deprecated `layout` option in the maven deploy plugin when specifying `altDeploymentRepository`, [as described here](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html) and [here](https://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-in-legacy-layout.html). This enforces a certain package directory structure which maven hasn't cared about for many moons. Remove this resolved the issue, which makes complete sense.

More specifically, our maven deploy command was something like this:
```
mvn deploy -DaltDeploymentRepository=nexus-release::default::https://out.nexus.com/repository/maven-releases 
```

and I removed the `layout` portion of the option like this:
```
mvn deploy -DaltDeploymentRepository=nexus-release::https://our.nexus.com/repository/maven-releases 
```

Supporting some long deprecated package structure, in my opinion, is not something you should have to do. 

Thanks again for your work. I'll close this now :tada:

**Comment by zolyfarkas** [comment]
@mpataki thanks for the explanation! this should help others encountering this.
