### ISSUE TITLE
Use @SafeVarargs to avoid user-side warnings

### ISSUE THREAD

**Issue by marinier** [zolyfarkas/spf4j#45]
I'm using Java 11 and Eclipse 2020-03.

If I do this in a unit test (taken from examples on this page: http://www.spf4j.org/spf4j-slf4j-test/index.html):

```java
LogAssert expect = TestLoggers.sys().expect("org.spf4j.test", Level.ERROR,
    LogMatchers.hasFormat("Booo"));
```

I get the warning:
`Type safety: A generic array of Matcher<TestLogRecord> is created for a varargs parameter`

I think this can be fixed by annotating `TestLoggers.expect()` (and other similar varargs methods) with `@SafeVarags`. Then callers won't get the error. Otherwise, callers have to add `@SuppressWarnings("unchecked")` in their own code.

See this article for more info on `@SafeVarags`: https://www.informit.com/articles/article.aspx?p=2861454&seqNum=7

**Comment by zolyfarkas** [comment]
Hi @marinier thanks for reporting this, 
Made the changes to 8.8.2-SNAPSHOT, please let me know if there is anything I missed.
thanks again!

**Comment by marinier** [comment]
It works!

Note I didn't see 8.8.2-SNAPSHOT posted anywhere, so I built it from source. And it turns out it refuses to build with Java 11 as-is, because it accesses `sun.misc` which is now internal-only. (I think you can work around it with `--add-modules jdk.unsupported`, but I just built it with Java 8.)

**Comment by zolyfarkas** [comment]
8.8.2-SNAPHSOT is published to maven central snapshot repo. There are sometimes lags.
Thanks for checking!

spf4j will transition to JDK 11 sometime this year. (spf4j release 11.0.0+…) 8.X will be in maintenance mode.

—Z
