### ISSUE TITLE
slf4j-test has easily confused property names

### ISSUE THREAD

**Issue by keturn** [zolyfarkas/spf4j#47]
It took me several readings before I noticed that some properties are

`spf4j.test.log.collect*` while others are 
`spf4j.testLog.root*`

one with the period separating "test" from "log" and the other with a capital **L**.

Reducing the confusion would shorten my "why isn't it showing up!" headaches. 🙂

**Comment by zolyfarkas** [comment]
agree. will fix.

**Comment by zolyfarkas** [comment]
fixed in 8.8.3
