### ISSUE TITLE
Using spf4j-slf4j-test for tests, but still logging with logback

### ISSUE THREAD

**Issue by marinier** [zolyfarkas/spf4j#53]
Is it possible to set up spf4j-slf4j-test such that I can test that certain log messages are produced, but still use logback for logging to the console in the same test (and all other tests in the project, most of which do not test log messages)?

**Comment by zolyfarkas** [comment]
That is not possible, spf4j-slf4j-test  is a complete log backend. The functionality in spf4j-slf4j-test is tailored specifically to fill all needs one would have regarding output in IDE and Build systems. I would interested in finding our more about what you are trying to do.

**Comment by marinier** [comment]
Ok. The reason I'd like to use spf4j is so I can test the logging in a few tests. However, the rest of the system is using logback at runtime, and thus it would be nice to be able to continue using the logback config files for testing, too, so developers don't have to keep track of two different config styles. So really, it's not so much that I want to use logback per se, so much as I want to use the logback config file.

**Comment by marinier** [comment]
I should also say, one of the things I like about logback is I can control what goes to std out vs. err. I have warnings and errors go to std err so they show up red in Eclipse's console output. Possible feature for spf4j?

**Comment by zolyfarkas** [comment]
ERROR logs  are going out to  STDERR, warnings not. 
I can make the level configurable, although warnings should not go to stderr. (usually stderr output is treated as ERROR...)

One of the things spf4j does, even if log output is set to INFO or higher,
the debug(or trace) level logs are captured (in a circular buffer) and dumped to your console in case of unit test failure.
This keeps your test output clean when everything is fine, and have the detail only when something goes wrong...

Also you can control log levels for output  with annotations and unit test level..

I am not sure how to square this behavior with logback...

**Comment by marinier** [comment]
For me, I like to put warnings to stderr too, because they often indicate real problems. That said, you're right, spf4j has some really cool logging features, and I probably just need to rethink how I typically approach logging in order to take best advantage of its capabilities.
