### ISSUE TITLE
spf4j-slf4j-test: where to put spf4j-test-prtcfg.properties?

### ISSUE THREAD

**Issue by marinier** [zolyfarkas/spf4j#54]
I tried putting it in src/test/resources, but nothing I put in there has any effect.

**Comment by zolyfarkas** [comment]
If you are running from the IDE, you would nee to use: spf4j-test-prtcfg-ide.properties
spf4j-test-prtcfg.properties applies outside of executions from IDE.

**Comment by zolyfarkas** [comment]
It should work, make sure you set the config to greedy (like: com.category=ERROR,true)
if you want only ERROR to be printed for com.category.

to troubleshoot you can put a breakpoint here: https://github.com/zolyfarkas/spf4j/blob/dae1de805effb42c68626d0d4c1cc9f96956f295/spf4j-slf4j-test/src/main/java/org/spf4j/test/log/TestLoggers.java#L105

**Comment by marinier** [comment]
I set a breakpoint in `TestLoggers` I can see that it is getting loaded. I actually did not switch to `spf4j-test-prtcfg-ide.properties`, because I don't want the logging to be any different between IDE and non-IDE.

I then added the greedy flag and now it's working!

A couple questions/comments:
* What does greedy mean? It's mentioned in the documentation, but never defined.
* When I first tried adding the greedy flag, I added it like this: `com.category=ERROR, true` (note the space before `true`). This actually caused an exception to be thrown. Ideally, the system would be insensitive to whitespace, but if that's hard, it would be nice to at least get an error message and let the system keep running vs. an exception (and if it can say what the problem actually is, even better).

**Comment by zolyfarkas** [comment]
Log Handlers are registered to a category:

"" -> handler 1
"a.b" -> handler 2
"a.b.c" - > handler 3

when you log a message with a.b.c category:

the following handlers will be called in the order: 3, 2, 1

a greedy handler will prevent the log message to be handled by the next handlers. (if handler 2 is greedy, only 3, 2 will execute)

I think all printing all handlers should greedy... now that I think of...

about the comma parsing, it is not hard, its just a shortcut I made at the time I implemented this.... feel free to do a PR about it...

**Comment by marinier** [comment]
That makes sense. Thanks for the explanation!
