### ISSUE TITLE
Bintray is now sunset

### ISSUE THREAD

**Issue by matJC** [zolyfarkas/spf4j#56]
[https://bintray.com/](https://bintray.com/)

Because bintray is now sunset, we are getting the following error when building our avro-schemas project:
```
[ERROR]     Unresolveable build extension: Plugin org.spf4j:maven-avro-schema-plugin:8.8.5 or one of its dependencies could not be resolved: Failed to collect dependencies at org.spf4j:maven-avro-schema-plugin:jar:8.8.5 -> org.spf4j:spf4j-maven-schema-resolver:jar:8.8.5 -> org.apache.avro:avro:jar:1.9.0.20p: Failed to read artifact descriptor for org.apache.avro:avro:jar:1.9.0.20p: Could not transfer artifact org.apache.avro:avro:pom:1.9.0.20p from/to bintray-zolyfarkas-core (https://dl.bintray.com/zolyfarkas/core): Access denied to: https://dl.bintray.com/zolyfarkas/core/org/apache/avro/avro/1.9.0.20p/avro-1.9.0.20p.pom , ReasonPhrase:Forbidden. -> [Help 2]
```

Our project is using the `maven-avro-schema-plugin` plugin.

**Comment by agnibha92** [comment]
Having Same Issue... is there any fix to it?

**Comment by zolyfarkas** [comment]
I have released a new version that does not reference bintray published packages anymore: 8.9.0 this should be the easiest fix. 

the packages are published to:

'''
        <repositories>
          <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/zolyfarkas/*</url>
            <snapshots>
              <enabled>true</enabled>
            </snapshots>
          </repository>
        </repositories>
        <pluginRepositories>
            <pluginRepository>
              <id>github</id>
              <url>https://maven.pkg.github.com/zolyfarkas/*</url>
              <snapshots>
                <enabled>true</enabled>
              </snapshots>
            </pluginRepository>
        </pluginRepositories>
'''
see for more detail: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

if you have any trouble, let me know, cheers!

**Comment by agnibha92** [comment]
Thanks @zolyfarkas For Your Prompt Support. :)

**Comment by agnibha92** [comment]
@zolyfarkas  Getting This Error Now

`[ERROR] Failed to execute goal on project bot-infra-common: Could not resolve dependencies for project io.gupshup:bot-infra-common:jar:1.0: Failed to collect dependencies at org.spf4j:spf4j-core:jar:8.9.0 -> org.spf4j.avro:core-schema:jar:1.0.3 -> org.apache.avro:avro:jar:1.10.0.1p: Failed to read artifact descriptor for org.apache.avro:avro:jar:1.10.0.1p: Could not transfer artifact org.apache.avro:avro:pom:1.10.0.1p from/to github (https://maven.pkg.github.com/zolyfarkas/*): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
`

**Comment by zolyfarkas** [comment]
try to add you your settings.xml:

    <server>
      <id>github</id>
      <username>your github username</username>
      <password>your github access token</password>
    </server>

this is a requirement for now until github removes the requirement: "We plan to offer this in the future but need to improve the service a bit before that"

for more info see: https://github.community/t/how-to-allow-unauthorised-read-access-to-github-packages-maven-repository/115517

**Comment by zolyfarkas** [comment]
Not a dumb question, 

Since this is a fork build and not an official one, I cannot publish it under the org.apache.avro maven groupId in maven central, where only official releases will be published. 

Now hopefully this authentication barrier will be temporary and github removes it as promised.
I have not been able to find a better alternative yet...

**Comment by bipul-git** [comment]
@zolyfarkas Isn't is working now. Giving 400

**Comment by esend7881** [comment]
Would you consider uploading it to https://jitpack.io/ instead? It is free for opensource and there are no authentication steps to deal with (we just need to reference jitpack in the POM as a repository).

Those steps of making a token are just a bit excessive, makes each system I work with needing an extra step, etc. 

Another open source project I work with that uses this (in case you wanted to see an example):
https://jitpack.io/#Juniper/netconf-java
https://github.com/Juniper/netconf-java

As you can see, the tags form the version.
